<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SHARMAPC-PC" name="Learning assertions" tests="1" failures="1" timestamp="23 Apr 2020 12:18:49 GMT" time="4.338" errors="0">
  <testcase name="testGoogleSearch" time="1.207" classname="tests.UsingAssertions">
    <failure type="java.lang.AssertionError" message="Error coming because of xyz reason expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error coming because of xyz reason expected [true] but found [false]
	at tests.UsingAssertions.testGoogleSearch(UsingAssertions.java:25)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testGoogleSearch -->
</testsuite> <!-- Learning assertions -->
